# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8083}
    context-path: /
    use-forward-headers: true
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript

logging.level.org.springframework.security: DEBUG


# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    
# LOGGING
#logging.level.org.springframework.security: DEBUG
---

spring:
  profiles: docker
  data:
    mongodb:
      host: auth-mongodb
      username: odrin7
      password: odrin7
      database: boardGameArena
      port: 27017

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

---
spring:
  profiles: standalone
  data:
    mongodb:
      host: 192.168.99.100
      username: odrin7
      password: odrin7
      database: boardGameArena
      port: 25000

# EUREKA
eureka:
  instance:
    hostname: 192.168.99.100
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
