# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8090}

spring:
    aop:
        proxyTargetClass: true
# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
# ZULL
zuul:
  routes:
    auth-service:
        path: /uaa/**
        url: http://auth-service:8083
        stripPrefix: false
        sensitiveHeaders:
    ui-service:
        sensitiveHeaders:
        path: /api/**
        stripPrefix: true
---
spring:
  profiles: docker

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

---
spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
