# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8085}
    context-path: /
    use-forward-headers: true
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript

# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: api-service
      clientSecret: api-service
      accessTokenUri: http://auth-service:8083/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        keyValue: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
              -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
#LOGGING
#logging.level.org.springframework.security: DEBUG

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

---

spring:
  profiles: docker
  data:
    mongodb:
      host: message-mongodb
      username: odrin7
      password: odrin7
      database: boardGameArena
      port: 27017

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

---

spring:
  profiles: standalone
  data:
    mongodb:
      host: 192.168.99.100
      username: odrin7
      password: odrin7
      database: boardGameArena
      port: 27017

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
